# 📊 Estadística y Probabilidad para Ciencias de la Tierra
## Módulo 1: Introducción a Python y Exploración de Datos

**Tema:** Importación y exploración de datos. Simulación de poblaciones y selección de muestras aleatorias.

---

### Objetivos de este notebook

Al finalizar esta sesión serás capaz de:

1. Escribir y ejecutar código Python básico dentro de un Jupyter Notebook.
2. Importar datos desde un archivo `.csv` y explorarlos con la librería `pandas`.
3. Calcular estadísticas descriptivas básicas (media, mediana, desviación estándar, etc.).

### Cómo usar este notebook

Un notebook de Jupyter está formado por **celdas**. Hay dos tipos que usaremos:

- **Celdas de texto (Markdown)**, como esta, con explicaciones, títulos, etc.
- **Celdas de código**, donde escribimos y ejecutamos instrucciones en Python.

Para ejecutar una celda, selecciónala y presiona **`Shift + Enter`** (o el botón ▶️ *Run*). Ejecuta las celdas en orden, de arriba hacia abajo — ¡no te saltes ninguna la primera vez!

---
# Parte 1 · Introducción a Python

Antes de trabajar con datos reales de ciencias de la Tierra, necesitamos conocer las herramientas básicas del lenguaje Python. Esta primera parte es una introducción rápida pensada para quienes nunca han programado.

## 1.1 Tu primera celda de código

En Python, la función `print()` muestra un mensaje en pantalla. Ejecuta la siguiente celda:

In [1]:
print("Bienvenida/o al curso de Estadística y Probabilidad.")

Bienvenida/o al curso de Estadística y Probabilidad.

También puedes usar Python como una calculadora: si una operación es la última línea de la celda, Jupyter muestra el resultado automáticamente (sin necesidad de `print`).

In [2]:
# Python como calculadora
15 + 27

42

## 1.2 Variables y tipos de datos

Una **variable** es un espacio en la memoria de la computadora donde guardamos un valor con un nombre. En Python se crea así:

```python
nombre_variable = valor
```

Los tipos de datos básicos que más usaremos son:

| Tipo | Nombre en Python | Ejemplo |
|---|---|---|
| Número entero | `int` | `12` |
| Número decimal | `float` | `12.5` |
| Texto (cadena) | `str` | `"Basalto"` |
| Verdadero/Falso | `bool` | `True`, `False` |

Podemos conocer el tipo de una variable con la función `type()`.

In [3]:
# Variables que describen una estación meteorológica
nombre_estacion = "Estación Chapultepec"
altitud_msnm = 2325          # metros sobre el nivel del mar (int)
temperatura_c = 18.7         # grados Celsius (float)
estacion_activa = True       # booleano

print(nombre_estacion)
print(type(nombre_estacion))
print(type(altitud_msnm))
print(type(temperatura_c))
print(type(estacion_activa))

Estación Chapultepec
<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

Creamos variables que describen una muestra de roca recolectada en campo y las mostramos con `print()`.

In [3]:
# Datos de una muestra de roca
id_muestra = "R-014"
tipo_roca = "Ígnea"
densidad_g_cm3 = 2.75
es_porosa = False

print("Muestra:", id_muestra)
print("Tipo de roca:", tipo_roca)
print("Densidad (g/cm3):", densidad_g_cm3)
print("¿Es porosa?:", es_porosa)

Muestra: R-014
Tipo de roca: Ígnea
Densidad (g/cm3): 2.75
¿Es porosa?: False

### Ejercicio para resolver:

Crea variables que describan un **sismo** registrado por una estación sismológica:

- `magnitud` → un número decimal, por ejemplo `4.8`
- `profundidad_km` → un número decimal
- `region` → un texto con el nombre de una región
- `fue_sentido` → un booleano (`True` o `False`)

Después imprime las cuatro variables usando `print()`.

In [5]:
# Tu código aquí
magnitud = ...
profundidad_km = ...
region = ...
fue_sentido = ...

# No olvides imprimir las variables

## 1.3 Operadores aritméticos

Python permite hacer operaciones matemáticas directamente:

| Operador | Significado | Ejemplo |
|---|---|---|
| `+` | Suma | `3 + 2` → `5` |
| `-` | Resta | `3 - 2` → `1` |
| `*` | Multiplicación | `3 * 2` → `6` |
| `/` | División | `3 / 2` → `1.5` |
| `**` | Potencia | `3 ** 2` → `9` |
| `%` | Módulo (residuo) | `7 % 2` → `1` |

### Ejercicio:

En geología, la **densidad** se calcula como masa entre volumen: $\rho = m / V$

In [6]:
masa_g = 152.4       # gramos
volumen_cm3 = 56.8    # cm^3

densidad = masa_g / volumen_cm3
print("Densidad de la muestra:", round(densidad, 2), "g/cm3")

Densidad de la muestra: 2.68 g/cm3

### Ejercicio para resolver:

La conversión de temperatura de grados Celsius a Fahrenheit es:

$$°F = °C \times \frac{9}{5} + 32$$

Convierte a Fahrenheit la temperatura `temperatura_c` que creaste antes (18.7 °C) y guárdala en una variable llamada `temperatura_f`. Imprime el resultado.

In [4]:
# Tu código aquí
temperatura_f = ...
print(temperatura_f)

Ellipsis

## 1.4 Listas

Una **lista** guarda varios valores en un solo objeto, en un orden específico. Se crean con corchetes `[]`.

In [6]:
# Temperaturas registradas durante una semana (°C)
temperaturas_semana = [16.2, 17.8, 15.9, 18.4, 19.1, 17.0, 16.5]

print(temperaturas_semana)

print("Número de datos:", len(temperaturas_semana))
print("Primer valor:", temperaturas_semana[0])
print("Último valor:", temperaturas_semana[-1])
print("Del segundo al cuarto:", temperaturas_semana[1:4])

[16.2, 17.8, 15.9, 18.4, 19.1, 17.0, 16.5]
Número de datos: 7
Primer valor: 16.2
Último valor: 16.5
Del segundo al cuarto: [17.8, 15.9, 18.4]

> 💡 En Python, los índices **empiezan en 0**: el primer elemento de la lista es `temperaturas_semana[0]`, no `[1]`.

Podemos calcular estadísticas simples sin librerías extra, usando funciones incorporadas:

In [9]:
print("Suma:", sum(temperaturas_semana))
print("Máximo:", max(temperaturas_semana))
print("Mínimo:", min(temperaturas_semana))
print("Promedio:", sum(temperaturas_semana) / len(temperaturas_semana))

Suma: 120.9
Máximo: 19.1
Mínimo: 15.9
Promedio: 17.271428571428572

### Ejercicio:

Agreguemos un nuevo dato a la lista con `.append()` y recalculemos el promedio.

In [7]:
temperaturas_semana.append(20.3)  # nuevo dato de un octavo día
print(temperaturas_semana)

[16.2, 17.8, 15.9, 18.4, 19.1, 17.0, 16.5, 20.3]

In [8]:
promedio_actualizado = sum(temperaturas_semana) / len(temperaturas_semana)
print("Nuevo promedio:", round(promedio_actualizado, 2))

Nuevo promedio: 17.65

### Ejercicio para resolver:

Se tiene la siguiente lista con las magnitudes de los últimos sismos registrados en una región:

```python
magnitudes = [3.2, 4.5, 2.8, 5.1, 3.9, 4.0, 2.5]
```

1. Crea la lista `magnitudes`.
2. Imprime cuántos sismos hay en total.
3. Imprime la magnitud máxima registrada.
4. Imprime el promedio de las magnitudes (redondeado a 2 decimales con `round()`).

In [11]:
# Tu código aquí
magnitudes = [3.2, 4.5, 2.8, 5.1, 3.9, 4.0, 2.5]

## 1.5 Diccionarios

Un **diccionario** guarda datos en pares `clave: valor`, muy útil para describir un objeto con varias propiedades. Se crean con llaves `{}`.

In [9]:
mineral = {
    "nombre": "Cuarzo",
    "dureza_mohs": 7,
    "color": "Incoloro a blanco",
    "sistema_cristalino": "Trigonal"
}

In [10]:
print(mineral["nombre"])
print(mineral["dureza_mohs"])

Cuarzo
7

In [11]:
# Agregar una nueva propiedad
mineral["brillo"] = "Vítreo"
print(mineral)

{'nombre': 'Cuarzo', 'dureza_mohs': 7, 'color': 'Incoloro a blanco', 'sistema_cristalino': 'Trigonal', 'brillo': 'Vítreo'}

### Ejercicio para resolver:

Crea un diccionario llamado `estacion` que describa una estación meteorológica, con al menos estas claves: `"nombre"`, `"altitud_m"`, `"temperatura_c"` y `"precipitacion_mm"`. Después imprime solo el valor de `"precipitacion_mm"`.

In [13]:
# Tu código aquí
estacion = {

}

## 1.6 Condicionales (`if`) y bucles (`for`)

Los **condicionales** ejecutan código solo si se cumple una condición:

```python
if condicion:
    # se ejecuta si la condición es verdadera
else:
    # se ejecuta si no
```

Los **bucles `for`** repiten una acción para cada elemento de una lista.

In [14]:
temperatura_hoy = 22.5

if temperatura_hoy > 20:
    print("Día cálido")
else:
    print("Día fresco")

Día cálido

In [15]:
for temp in temperaturas_semana:
    if temp > 18:
        print(temp, "-> cálido")
    else:
        print(temp, "-> fresco")

16.2 -> fresco
17.8 -> fresco
15.9 -> fresco
18.4 -> cálido
19.1 -> cálido
17.0 -> fresco
16.5 -> fresco
20.3 -> cálido

### Ejercicio:

Contemos cuántos días de la semana fueron "cálidos" (mayores a 18 °C) usando un bucle `for` y un contador.

In [16]:
contador_dias_calidos = 0

for temp in temperaturas_semana:
    if temp > 18:
        contador_dias_calidos = contador_dias_calidos + 1

print("Días cálidos:", contador_dias_calidos, "de", len(temperaturas_semana))

Días cálidos: 3 de 8

### Ejercicio para resolver:

Usando la lista `magnitudes` que creaste antes, escribe un bucle `for` que cuente cuántos sismos tuvieron una magnitud **mayor o igual a 4.0** (considerados moderados o mayores). Guarda el resultado en una variable llamada `sismos_moderados`.

In [17]:
# Tu código aquí
sismos_moderados = 0

for magnitud in magnitudes:
    # completa la condición
    ______________________

print(sismos_moderados)

0

## 1.7 Funciones

Una **función** agrupa código que queremos reutilizar. Se define con `def` y puede recibir *argumentos* y devolver un resultado con `return`.

In [12]:
def celsius_a_kelvin(temp_c):
    '''Convierte una temperatura de grados Celsius a Kelvin.'''
    return temp_c + 273.15

In [14]:
print(celsius_a_kelvin(0))
print(celsius_a_kelvin(25))

273.15
298.15

### Ejercicio para resolver:

Escribe una función llamada `densidad` que reciba `masa` y `volumen` como argumentos y devuelva la densidad (masa / volumen). Pruébala con `masa=100` y `volumen=40`.

In [19]:
# Tu código aquí
def densidad(masa, volumen):
    ...

# Prueba tu función

## 1.8 Librerías: NumPy y pandas

Una **librería** (o módulo) es un conjunto de funciones ya escritas por otras personas que podemos reutilizar. Para usarlas, primero hay que **importarlas**. Las dos librerías más importantes en este curso son:

- **NumPy** (`numpy`): cálculo numérico y arreglos (*arrays*).
- **pandas** (`pandas`): manejo de tablas de datos (`DataFrame`s), similar a Excel pero mucho más potente.

También usaremos **Matplotlib** para hacer gráficas.

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("Librerías importadas correctamente ✅")
print("Versión de NumPy:", np.__version__)
print("Versión de pandas:", pd.__version__)

Librerías importadas correctamente ✅
Versión de NumPy: 2.1.2
Versión de pandas: 2.2.3

Con NumPy podemos crear **arreglos**, que son como listas pero permiten hacer operaciones matemáticas sobre todos sus elementos a la vez (esto se llama *vectorización*):

In [17]:
temperaturas_array = np.array(temperaturas_semana)
temperaturas_array

array([16.2, 17.8, 15.9, 18.4, 19.1, 17. , 16.5, 20.3])

In [21]:
print("Media:", np.mean(temperaturas_array))
print("Desviación estándar:", np.std(temperaturas_array))
print("En Fahrenheit:", temperaturas_array * 9/5 + 32)

[16.2 17.8 15.9 18.4 19.1 17.  16.5 20.3]
Media: 17.65
Desviación estándar: 1.4413535305399576
En Fahrenheit: [61.16 64.04 60.62 65.12 66.38 62.6  61.7  68.54]

Con esto ya tenemos las bases de Python que necesitamos. ¡Vamos a trabajar con datos reales de ciencias de la Tierra!

---
# Parte 2 · Importación y exploración de datos

## 2.1 ¿Qué es un DataFrame?

En `pandas`, un **DataFrame** es una tabla de datos con filas y columnas, igual que una hoja de cálculo. Cada columna puede tener un tipo de dato distinto (texto, números, fechas, etc.) y cada fila normalmente representa una observación (por ejemplo, una muestra de roca o una estación).

## 2.2 Nuestro conjunto de datos: muestras de roca de campo

Imagina que un equipo de geología hizo una campaña de campo en distintos sitios de México, recolectando muestras de roca y midiendo su densidad, porosidad y dureza. Vamos a generar ese conjunto de datos (como si fuera el archivo que el equipo entregó) y guardarlo como un archivo `.csv`, el formato más común para compartir datos tabulares.

> En un caso real, tú recibirías directamente el archivo `.csv` y solo harías el paso de **lectura** de la sección 2.3. Aquí lo generamos nosotros primero, únicamente para tener datos con los que practicar.

In [18]:
np.random.seed(42)  # para que todas/os obtengamos los mismos datos "aleatorios"

sitios = ["Sierra de Guadalupe", "Valle de Bravo", "Pico de Orizaba",
          "Cañón del Sumidero", "Desierto de los Leones", "Malinalco"]

n_muestras = 120

tipo_roca = np.random.choice(
    ["Ígnea", "Sedimentaria", "Metamórfica"],
    size=n_muestras,
    p=[0.4, 0.35, 0.25]
)

# La densidad y la porosidad dependen del tipo de roca (con variación aleatoria)
densidad = np.where(
    tipo_roca == "Ígnea", np.random.normal(2.9, 0.15, n_muestras),
    np.where(tipo_roca == "Sedimentaria", np.random.normal(2.4, 0.2, n_muestras),
             np.random.normal(2.75, 0.18, n_muestras))
)

porosidad = np.where(
    tipo_roca == "Sedimentaria", np.random.normal(18, 5, n_muestras),
    np.random.normal(6, 2.5, n_muestras)
)
porosidad = np.clip(porosidad, 0.5, None)  # la porosidad no puede ser negativa

dureza_mohs = np.round(np.random.uniform(2, 7, n_muestras), 1)
profundidad_m = np.round(np.random.uniform(0.5, 15, n_muestras), 1)
sitio_muestreo = np.random.choice(sitios, size=n_muestras)

df_rocas = pd.DataFrame({
    "id_muestra": [f"R-{i:03d}" for i in range(1, n_muestras + 1)],
    "sitio": sitio_muestreo,
    "tipo_roca": tipo_roca,
    "densidad_g_cm3": np.round(densidad, 2),
    "porosidad_pct": np.round(porosidad, 1),
    "dureza_mohs": dureza_mohs,
    "profundidad_m": profundidad_m
})

df_rocas.to_csv("muestras_rocas_campo.csv", index=False)
print("Archivo 'muestras_rocas_campo.csv' creado con", len(df_rocas), "muestras.")

Archivo 'muestras_rocas_campo.csv' creado con 120 muestras.

## 2.3 Lectura de datos con `pd.read_csv()`

### Ejercicio:

Ahora sí, leamos el archivo `.csv` como lo haríamos con cualquier conjunto de datos real:

In [20]:
df = pd.read_csv("muestras_rocas_campo.csv")
df

,id_muestra,sitio,tipo_roca,densidad_g_cm3,porosidad_pct,dureza_mohs,profundidad_m
0,R-001,Desierto de los Leones,Ígnea,2.79,6.8,5.3,10.7
1,R-002,Cañón del Sumidero,Metamórfica,2.63,5.5,3.0,13.9
2,R-003,Desierto de los Leones,Sedimentaria,2.34,15.3,3.5,3.1
3,R-004,Desierto de los Leones,Sedimentaria,2.55,14.0,6.5,8.7
4,R-005,Sierra de Guadalupe,Ígnea,2.94,6.6,2.1,13.8
...,...,...,...,...,...,...,...
115,R-116,Sierra de Guadalupe,Metamórfica,2.58,5.1,4.4,4.3
116,R-117,Pico de Orizaba,Metamórfica,2.66,7.8,3.1,11.0
117,R-118,Desierto de los Leones,Ígnea,3.48,7.1,6.9,7.7
118,R-119,Sierra de Guadalupe,Metamórfica,2.74,5.1,6.7,1.7
119,R-120,Desierto de los Leones,Sedimentaria,2.22,26.4,2.2,3.7

## 2.4 Exploración inicial

Antes de analizar cualquier dato, siempre conviene revisar su estructura general.

### Ejercicio

In [21]:
print("Dimensiones (filas, columnas):", df.shape)
print("\nNombres de columnas:")
print(df.columns.tolist())
print("\nTipos de dato por columna:")
print(df.dtypes)

Dimensiones (filas, columnas): (120, 7)

Nombres de columnas:
['id_muestra', 'sitio', 'tipo_roca', 'densidad_g_cm3', 'porosidad_pct', 'dureza_mohs', 'profundidad_m']

Tipos de dato por columna:
id_muestra         object
sitio              object
tipo_roca          object
densidad_g_cm3    float64
porosidad_pct     float64
dureza_mohs       float64
profundidad_m     float64
dtype: object

In [22]:
df.head()   # primeras 5 filas

,id_muestra,sitio,tipo_roca,densidad_g_cm3,porosidad_pct,dureza_mohs,profundidad_m
0,R-001,Desierto de los Leones,Ígnea,2.79,6.8,5.3,10.7
1,R-002,Cañón del Sumidero,Metamórfica,2.63,5.5,3.0,13.9
2,R-003,Desierto de los Leones,Sedimentaria,2.34,15.3,3.5,3.1
3,R-004,Desierto de los Leones,Sedimentaria,2.55,14.0,6.5,8.7
4,R-005,Sierra de Guadalupe,Ígnea,2.94,6.6,2.1,13.8

In [23]:
df.info()   # resumen general: tipos, nulos, memoria

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_muestra      120 non-null    object
 1   sitio           120 non-null    object
 2   tipo_roca       120 non-null    object
 3   densidad_g_cm3  120 non-null    float64
 4   porosidad_pct   120 non-null    float64
 5   dureza_mohs     120 non-null    float64
 6   profundidad_m   120 non-null    float64
dtypes: float64(4), object(3)
memory usage: 6.7+ KB

### Ejercicio para resolver:

1. Muestra las **últimas 3 filas** del DataFrame usando `.tail()`.
2. Imprime cuántas columnas tiene el DataFrame (usando `df.shape`).
3. ¿Hay valores nulos en el DataFrame? Investígalo con `df.isnull().sum()`.